apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
      - name: myapp

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: {{ .Values.containerPort }}

        env:
        - name: ENVIRONMENT
          value: "{{ .Values.env.ENVIRONMENT }}"

        - name: APP_VERSION
          value: "{{ .Values.env.APP_VERSION }}"

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

        livenessProbe:
          httpGet:
            path: /health
            port: 5000